version: '2.1'

services:
  database:
    image: "microservice-users-and-teams/database"
    environment:
      - MYSQL_DATABASE=lozzikitUsers
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3308:3306
    healthcheck:
      test: ["CMD", "mysql", "--user=root", "--password=root", "--execute=SHOW DATABASES;"]
      interval: 10s
      retries: 3
  server:
    image: microservice-users-and-teams/server
    ports:
      - 8080:8080
      - 5005:5005
    environment:
      - DATABASE_HOST=database
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=lozzikitUsers
      - DATABASE_PORT=3306
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-sSfk", "http://localhost:8080/api/health"]
      interval: 10s
      timeout: 10s
      retries: 3